AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/CollectionLiteralLength:
  Exclude:
    - 'data/**/*'
